import { AppProvider } from "@/components/AppContext";
import Header from "@/components/layout/Header";
import { Roboto } from "next/font/google";
import './globals.css'
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-6xl p-4 mx-auto">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className='max-w-2xl p-4 mx-auto mt-8 text-center text-gray-500 border-t'>
              &copy; Minmgf
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
